### ISSUE TITLE
Mobile menu doesn't close when subsection link is clicked

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js/markojs-website#18]
**Steps to reproduce**
1. Go to the website in mobile view
2. Click the hamburger menu to open up the `mobile menu`
3. Click on `Installing`
4. Open up the `mobile menu` again, and then click on `Trying out Marko`.
5. Notice how the mobile menu doesn't close

This seems to apply to clicking any links that don't cause a full-page refresh.

Let me know if this is a valid issue. I can work on it if it is.

**Comment by austinkelleher** [comment]
Nice find @newyork-anthonyng. I agree that the mobile menu should close when clicking a section that does not require a page refresh. Go ahead and take this one if you want! 👍

**Comment by austinkelleher** [comment]
@newyork-anthonyng Thanks for all the hard work. I gave you write access to this repo. Feel free to make changes. We really appreciate your help!
