### ISSUE TITLE
Remove or compress large React logo

### ISSUE THREAD

**Issue by robcalcroft** [marko-js/markojs-website#6]
There's a 338kb image of the React logo that is served to users. It surely doesn't need to be that big? Looks like its having some serious perf impact on load speed! 🐌 
![Large image screenshot](http://i.imgur.com/0aJMRrz.png)

**Comment by austinkelleher** [comment]
Thanks for reporting. I agree, and I've scaled the React logo down. Most of the logos on the website are used for the benchmark component at the bottom of main page. We do not need the large logos and we could scale the remaining logos down to reasonable sizes too.

**Comment by robcalcroft** [comment]
Looks good 👌

**Comment by austinkelleher** [comment]
@robcalcroft if you're interested in any further optimizations (e.g. scaling down other images to reasonable sizes), feel free to open a PR! Thanks again.
