### ISSUE TITLE
Error message "Error: Not allowed" appears when clicks "Show all browsers"

### ISSUE THREAD

**Issue by boshido** [marko-js/markojs-website#8]
Browser 
  - Google chrome "56.0.2924.87 (64-bit)"

OS
  - OS X EL CAPITAN

When I click the "Show all browers" the error appears and can not do any actions after that
![screen shot 2560-03-29 at 6 12 25 pm](https://cloud.githubusercontent.com/assets/3489862/24451972/4bc5dfe8-14ab-11e7-88fd-c7a89b5e203d.png)

Silky smooth stop perform animation
![image](https://cloud.githubusercontent.com/assets/3489862/24452033/8ee862fa-14ab-11e7-8587-4524235013e7.png)

**Comment by austinkelleher** [comment]
This looks to be fixed. Thanks for reporting the issue.
